### ISSUE TITLE
Add support for multiple push branches

### ISSUE THREAD

**Issue by vmaggioli** [philips-software/docker-ci-scripts#46]
We are going to be following the [Gitflow](https://www.atlassian.com/git/tutorials/comparing-workflows/gitflow-workflow) development model which means we'll need to be able to push our docker images for multiple branches such as `master` and `develop`. I'm willing to put up the PR for the work, just wondering if there might be any specifics behind why this shouldn't be supported

**Comment by JeroenKnoops** [comment]
I see no problems in adding this feature
